---
apiVersion: apps/v1
Kind: Deployment
metadata: 
  name: reddit-clone-deployment
spec:
  replicas: 3
  selectors:
    matchLabels:
      app: redditclone
  template:
    metadata: 
      name: reddit-clone-pod
      labels:
         app: redditclone
    spec:
      containers:
        - name: reddit-clone-container
          image: javeedit/redditclone
          ports:
          - containersPort: 3000
...