---
apiVersion: apps/v1
Kind: Deployment
metadata: 
  name: reddit-clone-deployment
spec:
  replicas: 3
  selectors:
    matchLabels:
      app: redditclone
  template:
    metadata: 
      name: reddit-clone-pod
      labels:
         app: redditclone
    spec:
      containers:
        - name: reddit-clone-container
          image: javeedit/redditclone
          ports:
          - containersPort: 3000
---
apiVersion: v1
Kind: Service
metadata: 
  name: reddit-clone-svc
spec: 
  type: NodePort
  selectors:
    app: redditclone
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
...